(cl:defpackage aro_msgs-msg
  (:use )
  (:export
   "<FOLLOWPATHACTION>"
   "FOLLOWPATHACTION"
   "<FOLLOWPATHACTIONFEEDBACK>"
   "FOLLOWPATHACTIONFEEDBACK"
   "<FOLLOWPATHACTIONGOAL>"
   "FOLLOWPATHACTIONGOAL"
   "<FOLLOWPATHACTIONRESULT>"
   "FOLLOWPATHACTIONRESULT"
   "<FOLLOWPATHFEEDBACK>"
   "FOLLOWPATHFEEDBACK"
   "<FOLLOWPATHGOAL>"
   "FOLLOWPATHGOAL"
   "<FOLLOWPATHRESULT>"
   "FOLLOWPATHRESULT"
   "<PATH>"
   "PATH"
  ))

