; Auto-generated. Do not edit!


(cl:in-package aro_msgs-msg)


;//! \htmlinclude FollowPathResult.msg.html

(cl:defclass <FollowPathResult> (roslisp-msg-protocol:ros-message)
  ((finalPosition
    :reader finalPosition
    :initarg :finalPosition
    :type geometry_msgs-msg:Pose2D
    :initform (cl:make-instance 'geometry_msgs-msg:Pose2D)))
)

(cl:defclass FollowPathResult (<FollowPathResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <FollowPathResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'FollowPathResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name aro_msgs-msg:<FollowPathResult> is deprecated: use aro_msgs-msg:FollowPathResult instead.")))

(cl:ensure-generic-function 'finalPosition-val :lambda-list '(m))
(cl:defmethod finalPosition-val ((m <FollowPathResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader aro_msgs-msg:finalPosition-val is deprecated.  Use aro_msgs-msg:finalPosition instead.")
  (finalPosition m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <FollowPathResult>) ostream)
  "Serializes a message object of type '<FollowPathResult>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'finalPosition) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <FollowPathResult>) istream)
  "Deserializes a message object of type '<FollowPathResult>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'finalPosition) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<FollowPathResult>)))
  "Returns string type for a message object of type '<FollowPathResult>"
  "aro_msgs/FollowPathResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'FollowPathResult)))
  "Returns string type for a message object of type 'FollowPathResult"
  "aro_msgs/FollowPathResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<FollowPathResult>)))
  "Returns md5sum for a message object of type '<FollowPathResult>"
  "9ed511beb5c491291b59853d2626b761")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'FollowPathResult)))
  "Returns md5sum for a message object of type 'FollowPathResult"
  "9ed511beb5c491291b59853d2626b761")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<FollowPathResult>)))
  "Returns full string definition for message of type '<FollowPathResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/Pose2D finalPosition~%~%================================================================================~%MSG: geometry_msgs/Pose2D~%# Deprecated~%# Please use the full 3D pose.~%~%# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.~%~%# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.~%~%~%# This expresses a position and orientation on a 2D manifold.~%~%float64 x~%float64 y~%float64 theta~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'FollowPathResult)))
  "Returns full string definition for message of type 'FollowPathResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%geometry_msgs/Pose2D finalPosition~%~%================================================================================~%MSG: geometry_msgs/Pose2D~%# Deprecated~%# Please use the full 3D pose.~%~%# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.~%~%# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.~%~%~%# This expresses a position and orientation on a 2D manifold.~%~%float64 x~%float64 y~%float64 theta~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <FollowPathResult>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'finalPosition))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <FollowPathResult>))
  "Converts a ROS message object to a list"
  (cl:list 'FollowPathResult
    (cl:cons ':finalPosition (finalPosition msg))
))
