// Generated by gencpp from file aro_msgs/PlanPathResponse.msg
// DO NOT EDIT!


#ifndef ARO_MSGS_MESSAGE_PLANPATHRESPONSE_H
#define ARO_MSGS_MESSAGE_PLANPATHRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace aro_msgs
{
template <class ContainerAllocator>
struct PlanPathResponse_
{
  typedef PlanPathResponse_<ContainerAllocator> Type;

  PlanPathResponse_()
    : path()  {
    }
  PlanPathResponse_(const ContainerAllocator& _alloc)
    : path(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector< ::geometry_msgs::Pose2D_<ContainerAllocator> , typename ContainerAllocator::template rebind< ::geometry_msgs::Pose2D_<ContainerAllocator> >::other >  _path_type;
  _path_type path;





  typedef boost::shared_ptr< ::aro_msgs::PlanPathResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aro_msgs::PlanPathResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PlanPathResponse_

typedef ::aro_msgs::PlanPathResponse_<std::allocator<void> > PlanPathResponse;

typedef boost::shared_ptr< ::aro_msgs::PlanPathResponse > PlanPathResponsePtr;
typedef boost::shared_ptr< ::aro_msgs::PlanPathResponse const> PlanPathResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aro_msgs::PlanPathResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aro_msgs::PlanPathResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::aro_msgs::PlanPathResponse_<ContainerAllocator1> & lhs, const ::aro_msgs::PlanPathResponse_<ContainerAllocator2> & rhs)
{
  return lhs.path == rhs.path;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::aro_msgs::PlanPathResponse_<ContainerAllocator1> & lhs, const ::aro_msgs::PlanPathResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace aro_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::aro_msgs::PlanPathResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aro_msgs::PlanPathResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aro_msgs::PlanPathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aro_msgs::PlanPathResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aro_msgs::PlanPathResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aro_msgs::PlanPathResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aro_msgs::PlanPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e29e087cb49b19f18f72937627f5d720";
  }

  static const char* value(const ::aro_msgs::PlanPathResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe29e087cb49b19f1ULL;
  static const uint64_t static_value2 = 0x8f72937627f5d720ULL;
};

template<class ContainerAllocator>
struct DataType< ::aro_msgs::PlanPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aro_msgs/PlanPathResponse";
  }

  static const char* value(const ::aro_msgs::PlanPathResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aro_msgs::PlanPathResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose2D[] path\n"
"\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::aro_msgs::PlanPathResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aro_msgs::PlanPathResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.path);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PlanPathResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aro_msgs::PlanPathResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aro_msgs::PlanPathResponse_<ContainerAllocator>& v)
  {
    s << indent << "path[]" << std::endl;
    for (size_t i = 0; i < v.path.size(); ++i)
    {
      s << indent << "  path[" << i << "]: ";
      s << std::endl;
      s << indent;
      Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "    ", v.path[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARO_MSGS_MESSAGE_PLANPATHRESPONSE_H
