// Generated by gencpp from file aro_msgs/FollowPathResult.msg
// DO NOT EDIT!


#ifndef ARO_MSGS_MESSAGE_FOLLOWPATHRESULT_H
#define ARO_MSGS_MESSAGE_FOLLOWPATHRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>

namespace aro_msgs
{
template <class ContainerAllocator>
struct FollowPathResult_
{
  typedef FollowPathResult_<ContainerAllocator> Type;

  FollowPathResult_()
    : finalPosition()  {
    }
  FollowPathResult_(const ContainerAllocator& _alloc)
    : finalPosition(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _finalPosition_type;
  _finalPosition_type finalPosition;





  typedef boost::shared_ptr< ::aro_msgs::FollowPathResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::aro_msgs::FollowPathResult_<ContainerAllocator> const> ConstPtr;

}; // struct FollowPathResult_

typedef ::aro_msgs::FollowPathResult_<std::allocator<void> > FollowPathResult;

typedef boost::shared_ptr< ::aro_msgs::FollowPathResult > FollowPathResultPtr;
typedef boost::shared_ptr< ::aro_msgs::FollowPathResult const> FollowPathResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::aro_msgs::FollowPathResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::aro_msgs::FollowPathResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::aro_msgs::FollowPathResult_<ContainerAllocator1> & lhs, const ::aro_msgs::FollowPathResult_<ContainerAllocator2> & rhs)
{
  return lhs.finalPosition == rhs.finalPosition;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::aro_msgs::FollowPathResult_<ContainerAllocator1> & lhs, const ::aro_msgs::FollowPathResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace aro_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::aro_msgs::FollowPathResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::aro_msgs::FollowPathResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aro_msgs::FollowPathResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::aro_msgs::FollowPathResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aro_msgs::FollowPathResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::aro_msgs::FollowPathResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::aro_msgs::FollowPathResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "9ed511beb5c491291b59853d2626b761";
  }

  static const char* value(const ::aro_msgs::FollowPathResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x9ed511beb5c49129ULL;
  static const uint64_t static_value2 = 0x1b59853d2626b761ULL;
};

template<class ContainerAllocator>
struct DataType< ::aro_msgs::FollowPathResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "aro_msgs/FollowPathResult";
  }

  static const char* value(const ::aro_msgs::FollowPathResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::aro_msgs::FollowPathResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"geometry_msgs/Pose2D finalPosition\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
;
  }

  static const char* value(const ::aro_msgs::FollowPathResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::aro_msgs::FollowPathResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.finalPosition);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct FollowPathResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::aro_msgs::FollowPathResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::aro_msgs::FollowPathResult_<ContainerAllocator>& v)
  {
    s << indent << "finalPosition: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.finalPosition);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ARO_MSGS_MESSAGE_FOLLOWPATHRESULT_H
