// Generated by gencpp from file my_package1/multiplier.msg
// DO NOT EDIT!


#ifndef MY_PACKAGE1_MESSAGE_MULTIPLIER_H
#define MY_PACKAGE1_MESSAGE_MULTIPLIER_H

#include <ros/service_traits.h>


#include <my_package1/multiplierRequest.h>
#include <my_package1/multiplierResponse.h>


namespace my_package1
{

struct multiplier
{

typedef multiplierRequest Request;
typedef multiplierResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct multiplier
} // namespace my_package1


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::my_package1::multiplier > {
  static const char* value()
  {
    return "a7d7d7065d45755acef7d4dcf908162a";
  }

  static const char* value(const ::my_package1::multiplier&) { return value(); }
};

template<>
struct DataType< ::my_package1::multiplier > {
  static const char* value()
  {
    return "my_package1/multiplier";
  }

  static const char* value(const ::my_package1::multiplier&) { return value(); }
};


// service_traits::MD5Sum< ::my_package1::multiplierRequest> should match
// service_traits::MD5Sum< ::my_package1::multiplier >
template<>
struct MD5Sum< ::my_package1::multiplierRequest>
{
  static const char* value()
  {
    return MD5Sum< ::my_package1::multiplier >::value();
  }
  static const char* value(const ::my_package1::multiplierRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_package1::multiplierRequest> should match
// service_traits::DataType< ::my_package1::multiplier >
template<>
struct DataType< ::my_package1::multiplierRequest>
{
  static const char* value()
  {
    return DataType< ::my_package1::multiplier >::value();
  }
  static const char* value(const ::my_package1::multiplierRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::my_package1::multiplierResponse> should match
// service_traits::MD5Sum< ::my_package1::multiplier >
template<>
struct MD5Sum< ::my_package1::multiplierResponse>
{
  static const char* value()
  {
    return MD5Sum< ::my_package1::multiplier >::value();
  }
  static const char* value(const ::my_package1::multiplierResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::my_package1::multiplierResponse> should match
// service_traits::DataType< ::my_package1::multiplier >
template<>
struct DataType< ::my_package1::multiplierResponse>
{
  static const char* value()
  {
    return DataType< ::my_package1::multiplier >::value();
  }
  static const char* value(const ::my_package1::multiplierResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // MY_PACKAGE1_MESSAGE_MULTIPLIER_H
